environment:
  TARGET: x86_64-pc-windows-msvc
  matrix:
    - PYTHON: "C:/Python35-x64"
    - PYTHON: "C:/Python36-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.msi"
  - start /wait msiexec /i rust-nightly-%TARGET%.msi INSTALLDIR="%CD%\rust-nightly-%TARGET%" /quiet /qn /norestart
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64
  - set PATH=%PATH%;%CD%/rust-nightly-%TARGET%/bin
  - rustc -V
  - cargo -V
  - set RUST_BACKTRACE=1
  - pip install numpy

build_script:
  - cargo build --verbose

test_script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - rustdoc --test README.md -L native="%PYTHON%\\libs" -L target/debug/deps/
  - pip install setuptools-rust
  - cd example
  - python setup.py install
  - python setup.py test
