[package]
name = "rust-parallel"
version = "0.1.0"
authors = ["Yuji Kanagawa <yuji.kngw.80s.revive@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "rust_parallel"

[dependencies]
blas-src = { version = "0.14", features = ["openblas"] }
ndarray = { version = "0.17", features = ["blas", "rayon"] }
numpy = { path = "../.." }
openblas-src = { version = "0.10", features = ["cblas", "system"] }
pyo3 = { version = "0.29.0", features = ["multiple-pymethods"] }
