[package]
name = "rust-linalg"
version = "0.1.0"
authors = ["Yuji Kanagawa <yuji.kngw.80s.revive@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "rust_linalg"

[dependencies]
ndarray-linalg = { version = "0.18.1", features = ["openblas-system"] }
numpy = { path = "../.." }
pyo3 = { version = "0.29.0" }
